name: Build

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Build with all versions that can load the nashorn standalone Jar:
        java: [ 8, 10, 17, 20 ]
    name: Java ${{ matrix.java }} build
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Drun.jvmArguments="-Xmx4048m -Xms1024m"
      - uses: actions/upload-artifact@v2
        with:
          name: delight-fileupload
          path: target/delight-fileupload-*.jar